### ISSUE TITLE
[JOSS Review] Fix citations DOIs

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#32]
In the JOSS paper [PDF](https://github.com/openjournals/joss-papers/blob/joss.04029/joss.04029/10.21105.joss.04029.pdf), the DOI's of the references at the end of the paper are not displayed correctly, often starting with a dead link.

**Comment by rickhelmus** [comment]
A couple of DOIs were incorrectly specified as full URLs in the `bib`, these [should be fixed now](https://github.com/rickhelmus/patRoon/commit/521587531f72fed72e398586e9d77b180d3dcd88).

I couldn't find any broken links though, I am curious if it's PDF viewer related?

**Comment by hechth** [comment]
The first reference and the `Exploring Information in Pubchem` links are still broken, otherwise everything is fine :).

**Comment by rickhelmus** [comment]
Ahrg! OK the PubChem DOI should be fixed now as well.

The first one is out of my control: tagging @HenrikBengtsson here. I copied your reference from the `future` package verbatim from [here](https://journal.r-project.org/archive/2021/RJ-2021-048/index.html), but the DOI seems to be unknown. Perhaps it got updated?

![image](https://user-images.githubusercontent.com/37015911/149503412-30c78680-803d-4a6c-989c-da6a95155ea1.png)

**Comment by hechth** [comment]
Alright, I think then either just remove the DOI or keep it there in the hope that it will be valid some day :)

**Comment by HenrikBengtsson** [comment]
Hi, sorry this one slipped off my todo list. Yes, that DOI is not yet activated. This is because there were some hiccups back in July causing this article to not end up in the R Journal volume that came out in July 2021.  I think the next volume will come out anytime now, so hopefully the DOI will work then.  

FWIW, until then, I put the DOI in a BibTeX `note` entry instead of in a `doi` entry, cf. https://cran.r-project.org/web/packages/future/citation.html.

**Comment by rickhelmus** [comment]
Hi Henrik,

Great, many thanks for the update. Hopefully the DOI will be active soon then.

**Comment by HenrikBengtsson** [comment]
FYI, the next R Journal issue was just released and the DOI for my future article is now working, cf. <https://doi.org/10.32614/RJ-2021-048>.

FWIW, I had a chat with Di Cook the other day about the DOIs not being available until the issue is actually released. That's an oversight, and she said she'll look into formally registering DOIs already when the preview of the article is available online.
